// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */

declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";

  interface DynamicRouter {
    "/table/[roomId]": InferRoute<import("./app/table/[roomId]/route-type").RouteType>;
  }

  interface StaticRouter {
    "/": StaticRoute;
  }
}
